
-- Create the table for bookmarks
create table public.bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.bookmarks enable row level security;

-- Create Policy: Users can view their own bookmarks
create policy "Users can view their own bookmarks"
on public.bookmarks for select
using (auth.uid() = user_id);

-- Create Policy: Users can insert their own bookmarks
create policy "Users can insert their own bookmarks"
on public.bookmarks for insert
with check (auth.uid() = user_id);

-- Create Policy: Users can delete their own bookmarks
create policy "Users can delete their own bookmarks"
on public.bookmarks for delete
using (auth.uid() = user_id);

-- Create Policy: Users can update their own bookmarks (Optional but good to have)
create policy "Users can update their own bookmarks"
on public.bookmarks for update
using (auth.uid() = user_id);
